src/Extensions/Portfolio/Entity/Serie.php
<?php

namespace App\Extensions\Portfolio\Entity;

use Beelab\TagBundle\Tag\TaggableInterface;
use Beelab\TagBundle\Tag\TagInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

use Artgris\Bundle\MediaBundle\Form\Validator\Constraint as MediaAssert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Extensions\Portfolio\Repository\SerieRepository")
 * @UniqueEntity("slug")
 * @ORM\HasLifecycleCallbacks
 */
class Serie implements TaggableInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $code;

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $labels = [
        "fr_FR" => "",
        "en_EN" => ""
    ];

    /**
     * @ORM\Column(type="boolean")
     */
    private $online;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cover_image;

    /**
     * @var string[]
     * @ORM\Column(type="array", nullable=true)
     * @MediaAssert\Image()
     */
    private $images = [];

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $descriptions = [
        "fr_FR" => "",
        "en_EN" => ""
    ];

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_sent;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Tag", inversedBy="series")
     */
    private $tags;

    private $tagsText;

    /**
     * @var \DateTimeInterface
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getLabels(): ?array
    {
        return $this->labels;
    }

    public function setLabels(array $labels): self
    {
        $this->labels = $labels;

        return $this;
    }

    public function getOnline(): ?bool
    {
        return $this->online;
    }

    public function setOnline(bool $online): self
    {
        $this->online = $online;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->cover_image;
    }

    public function setCoverImage(?string $cover_image): self
    {
        $this->cover_image = $cover_image;

        return $this;
    }

    public function getImages(): ?array
    {
        return $this->images;
    }

    public function setImages(?array $images): self
    {
        $this->images = $images;

        return $this;
    }

    public function getDescriptions(): ?array
    {
        return $this->descriptions;
    }

    public function setDescriptions(?array $descriptions): self
    {
        $this->descriptions = $descriptions;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getDateSent()
    {
        return $this->date_sent;
    }
    /**
     * @param mixed $date_sent
     */
    public function setDateSent($date_sent): void
    {
        $this->date_sent = $date_sent;
    }
    /**
     * @ORM\PrePersist
     */
    public function onPrePersistSetRegistrationDate()
    {
        $this->date_sent = new \DateTime();
    }

    public function addTag(TagInterface $tag): void
    {
        if (!$this->tags->contains($tag)) {
            $this->tags->add($tag);
        }
    }

    public function removeTag(TagInterface $tag): void
    {
        $this->tags->removeElement($tag);
    }

    public function hasTag(TagInterface $tag): bool
    {
        return $this->tags->contains($tag);
    }

    public function getTags(): iterable
    {
        return $this->tags;
    }

    public function getTagNames(): array
    {
        return empty($this->tagsText) ? [] : \array_map('trim', explode(',', $this->tagsText));
    }

    public function setTagsText(?string $tagsText): void
    {
        $this->tagsText = $tagsText;
        $this->updated = new \DateTimeImmutable();
    }

    public function getTagsText(): ?string
    {
        $this->tagsText = \implode(', ', $this->tags->toArray());

        return $this->tagsText;
    }
}

src/Extensions/Portfolio/Form/SerieType.php
<?php

namespace App\Extensions\Portfolio\Form;

use App\Extensions\Portfolio\Entity\Serie;
use Artgris\Bundle\MediaBundle\Form\Type\MediaCollectionType;
use Artgris\Bundle\MediaBundle\Form\Type\MediaType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SerieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('code')
            ->add('labels')
            ->add('online')
            ->add('slug')
            ->add('cover_image',MediaType::class, [
                'conf' => 'default'
            ])
            ->add('images', MediaCollectionType::class, [
                'conf' => 'default'
            ])
            ->add('descriptions')
            ->add('tagsText', TextType::class, ['required' => false, 'label' => 'Tags'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Serie::class,
        ]);
    }
}

src/Extensions/Portfolio/Controller/SerieController.php
<?php

namespace App\Extensions\Portfolio\Controller;

use App\Extensions\Portfolio\Entity\Serie;
use App\Extensions\Portfolio\Form\SerieType;
use App\Extensions\Portfolio\Repository\SerieRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/extension/portfolio/serie")
 */
class SerieController extends AbstractController
{
    /**
     * @Route("/", name="serie_index", methods={"GET"})
     */
    public function index(SerieRepository $serieRepository): Response
    {
        return $this->render('@damnPortfolio/serie/index.html.twig', [
            'series' => $serieRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="serie_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $serie = new Serie();
        $form = $this->createForm(SerieType::class, $serie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($serie);
            $entityManager->flush();

            return $this->redirectToRoute('serie_index');
        }

        return $this->render('@damnPortfolio/serie/new.html.twig', [
            'serie' => $serie,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="serie_show", methods={"GET"})
     */
    public function show(Serie $serie): Response
    {
        return $this->render('@damnPortfolio/serie/show.html.twig', [
            'serie' => $serie,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="serie_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Serie $serie): Response
    {
        $form = $this->createForm(SerieType::class, $serie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('serie_index', [
                'id' => $serie->getId(),
            ]);
        }

        return $this->render('@damnPortfolio/serie/edit.html.twig', [
            'serie' => $serie,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="serie_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Serie $serie): Response
    {
        if ($this->isCsrfTokenValid('delete'.$serie->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($serie);
            $entityManager->flush();
        }

        return $this->redirectToRoute('serie_index');
    }
}

src/Extensions/Portfolio/templates/serie/_delete_form.html.twig
<form method="post" action="{{ path('serie_delete', {'id': serie.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ serie.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

src/Extensions/Portfolio/templates/serie/_form.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}
{{ form_start(form) }}
{{ form_row(form._token) }}
<div class="alert">
    {{ form_errors(form) }}
</div>
<div class="row">
    <div class="col">
        {% if button_label is defined and button_label == "Update" %}
            {{ form_row(form.code, {attr: {'readonly':'readonly'}}) }}
        {% else %}
            {{ form_row(form.code) }}
        {% endif %}
    </div>
    <div class="col" id="some-custom-id">
        {{ form_row(form.slug) }}
    </div>
    <div class="col" id="some-custom-id">
        {{ form_row(form.online) }}
    </div>
    <div class="col" id="some-custom-id">
        {{ form_row(form.tagsText) }}
    </div>
</div>
<div id="labels">
    <span style="font-size: 24px;">Labels</span>
    {% for locale, value in form.labels %}
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text" id="">{{ locale }}</span>
            </div>
            <input type="text" name="serie[labels][{{ locale }}]" value="{% if serie.labels[locale] is defined %}{{ serie.labels[locale] }}{% endif %}" class="form-control">
        </div>
    {% endfor %}
</div>
<hr>
<div id="descriptions">
    <span style="font-size: 24px;">Descriptions</span>
    {% for locale, value in form.descriptions %}
        <div class="form-group">
            <label for="serie[descriptions][{{ locale }}]">{{ locale }}</label>
            <textarea class="form-control" id="serie[descriptions][{{ locale }}]" name="serie[descriptions][{{ locale }}]" rows="3">{% if serie.descriptions[locale] is defined %}{{ serie.descriptions[locale] }}{% endif %}</textarea>
        </div>
    {% endfor %}
</div>
<br>
{{ form_row(form.cover_image) }}
{{ form_row(form.images) }}
<div class="text-center">
    <button class="btn btn-success ">{{ button_label|default('Save') }}</button>
</div>
{# don't render unrendered fields #}
{{ form_end(form, {'render_rest': false}) }}

src/Extensions/Portfolio/templates/serie/edit.html.twig
{% extends 'admin/layout.html.twig' %}

{% block title %}Edit Serie{% endblock %}

{% block body %}
    <h1>Edit: {{ serie.labels.fr_FR }}</h1>
    <hr>
    <div class="card card-body">
        {{ include('@damnPortfolio/serie/_form.html.twig', {'button_label': 'Update'}) }}
        <a class="btn btn-primary mt-5" href="{{ path('serie_index') }}">back to list</a>
    </div>
{% endblock %}


{% block javascript %}
    {#  Bootstrap #}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    {#  Jqueri UI #}
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
    {# jquery.collection.js #}
    <script type="text/javascript" src="{{ asset('js/jquery.collection.js') }}"></script>
    {# Import fengyuanchen/cropper #}
    <script src="{{ asset('bundles/artgrismedia/libs/cropperjs-1.4.1/cropper.min.js') }}"></script>
    {# Then the default bundle's JavaScript: #}
    {% include '@ArtgrisMedia/assets/include_js.html.twig' %}
{% endblock %}

src/Extensions/Portfolio/templates/serie/index.html.twig
{% extends 'admin/layout.html.twig' %}

{% block title %}Serie index{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-8 text-left"><h1>Series</h1></div>
        <div class="col-md-4 text-right"><a class="btn btn-success" href="{{ path('serie_new') }}">Create new</a></div>
    </div>
    <div class="row">
        {% for serie in series %}
            <div class="col-md-3">
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="{{ serie.coverImage ? asset(serie.coverImage)| imagine_filter('card_scale_filter') : "" }}" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">{{ serie.labels ? serie.labels.fr_FR : '' }}</h5>
                        <p class="card-text">{{ serie.descriptions ? serie.descriptions.fr_FR : '' }}</p>
                        <a class="btn btn-primary" href="{{ path('serie_show', {'id': serie.id}) }}">show</a>
                        <a class="btn btn-secondary" href="{{ path('serie_edit', {'id': serie.id}) }}">edit</a>
                    </div>
                </div>
            </div>
        {% else %}
            <div class="col-md-12">
                No records found
            </div>
        {% endfor %}
    </div>
{% endblock %}

src/Extensions/Portfolio/templates/serie/new.html.twig
{% extends 'admin/layout.html.twig' %}

{% block title %}Create Serie{% endblock %}

{% block body %}
    <h1>New Serie</h1>
    <hr>
    <div class="card card-body">
        {{ include('@damnPortfolio/serie/_form.html.twig') }}

        <a class="btn btn-primary mt-5" href="{{ path('serie_index') }}">back to list</a>
    </div>
{% endblock %}


{% block javascript %}
{#  Bootstrap #}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
{#  Jqueri UI #}
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
{# jquery.collection.js #}
<script type="text/javascript" src="{{ asset('js/jquery.collection.js') }}"></script>
{# Import fengyuanchen/cropper #}
<script src="{{ asset('bundles/artgrismedia/libs/cropperjs-1.4.1/cropper.min.js') }}"></script>
{# Then the default bundle's JavaScript: #}
{% include '@ArtgrisMedia/assets/include_js.html.twig' %}
{% endblock %}

src/Extensions/Portfolio/templates/serie/show.html.twig
{% extends 'admin/layout.html.twig' %}

{% block title %}Serie{% endblock %}

{% block body %}

    <div class="container-fluid">
        <div class="text-center">
            <h1>Serie: {{ serie.labels.fr_FR }}</h1>
        </div>
        <hr>
        <div class="row">
            <div class="col-md-4">
                <b>Code:</b> {{ serie.code }}
            </div>
            <div class="col-md-4">
                <b>Name:</b> {{ serie.labels.fr_FR }}
            </div>
            <div class="col-md-4">
                    <b><span class="{{ serie.online ? 'text-success' : 'text-danger' }}">{{ serie.online ? 'Online' : 'Offline' }}</span></b>
            </div>
            <div class="col-md-4">
                <b>URL:</b> {{ serie.slug }}
            </div>
            <div class="col-md-4">
                <b>Tags:</b> {% for tag in serie.tags %}<span class="badge badge-info m-2">{{ tag }}</span>{% endfor %}
            </div>
            <div class="col-md-4">
                <b>Date sent:</b> {{ serie.dateSent ? serie.dateSent|date('Y-m-d H:i:s') : '' }}
            </div>
            <div class="col-md-12">
                <b>Description:</b>
                <p>{{ serie.descriptions.fr_FR|raw }}</p>
            </div>
        </div>

        <div class="row">
            <div class="text-center col-md-6">
                <img style="max-width: 100%; max-height: 450px;" src="{{ asset(serie.coverImage) }}" />
                <p>(cover image)</p>
            </div>

            <div class="d-flex justify-content-center col-md-6">
                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" style="max-width:350px;">
                    <ol class="carousel-indicators">
                        {% set firstOccurence = "0" %}
                        {% for image in serie.images %}
                            <li data-target="#carouselExampleIndicators" data-slide-to="{{ firstOccurence }}" class="{% if firstOccurence == 0 %}active{% endif %}"></li>
                            {% set firstOccurence = firstOccurence+1 %}
                        {% endfor %}
                    </ol>
                    <div class="carousel-inner">
                        {% set secondOccurence = "0" %}
                        {% for image in serie.images %}
                            <div class="carousel-item {% if secondOccurence == 0 %}active{% endif %}">
                                <img class="d-block w-100" src="{{ asset(image) }}" alt="First slide">
                            </div>
                            {% set secondOccurence = secondOccurence+1 %}
                        {% endfor %}
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="row pt-4">
        <div class="col-md-4 text-left"><a class="btn btn-secondary" href="{{ path('serie_index') }}">back to list</a></div>
        <div class="col-md-4 text-center"><a class="btn btn-primary" href="{{ path('serie_edit', {'id': serie.id}) }}">edit</a></div>
        <div class="col-md-4 text-right">{{ include('@damnPortfolio/serie/_delete_form.html.twig') }}</div>
    </div>
{% endblock %}